sudo: false
language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: npm@benseager.co.uk
  api_key:
    secure: f96aaHO38CkXYdP88qzMRZHpMxTEjwZPZR04YqSyoBNWR2PXyKM86KU7k0rkzA1Gb1XYOayqJpcaLC6YQV+rqKNRBU54ANMhOIg6lTTJaxKQcw8wFzc0/b1zz5+wKFudHzdLcMe+J9FZ7a/C+Apy4FvawVtQt5Q9W7zepOpEItm01TW3uLXRGdc2jqVVgMFIAiKx5/zY+2B6Lb9GDJ/fmPnzXtKFsf3k4IpjIxygqIPh7w0+kd8J1btzKvIuBvl2JtRuuQKuudGt3ntvlUL4CYqdZgtfpWdHoFhCMxoBOnb7lfOn0S3DwLfWB6kyC1ToD34eF9IMrXq45uaCSuK8hxAwFNSALtDWfvVrD2GXP5z2b0+mR9Z5v/LdIu5xHGQ9TK+iIwrRdVyyWs1WBJgKOhTtS53nZjNGSMndlN1pxW/LbDemfaMv3xe2RYb+2tn1V8YHV07DxvsnXn2qhy4XPep2+fxWOI80od5K7ccJJjFiRMiTbqe6c+km84WLmas5AJOl3iEV8uqZrHQuBWXTeM/AJ+VbVo0A3nt562dzBRjKMHZxXIQc+cASYYDTbgcDfIcxquOgh+uxsAvJBAn3GE/bFNchsuVtRrPcpOaCMTaz3d0yiYBtYIa956j9obMGA9W4F93eHklCvTQzoI7CyRKBmXTn2oeoWyKFtgdRqbk=
